---
# purpose: YAML style policy for the hybridops.common collection
# adr: ADR-0606-ansible-collections-release-process
# maintainer: HybridOps.Tech

extends: default

rules:
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
    ignore-shebangs: true
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  document-start: disable
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  truthy:
    check-keys: false
